import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedagewidget/generated/GeneratedButtonsWidget8.dart';
import 'package:flutterapp/gymtrainerappapp/generatedagewidget/generated/GeneratedTextWidget19.dart';
import 'package:flutterapp/gymtrainerappapp/generatedagewidget/generated/GeneratedSpinnerWidget4.dart';

/* Frame Age
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAgeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 714.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 54.0,
                child: GeneratedButtonsWidget8(),
              ),
              Positioned(
                left: 131.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 350.00006103515625,
                child: GeneratedSpinnerWidget4(),
              ),
              Positioned(
                left: 53.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 269.0,
                height: 58.0,
                child: GeneratedTextWidget19(),
              )
            ]),
      ),
    ));
  }
}
