import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedweightwidget/generated/GeneratedButtonsWidget7.dart';
import 'package:flutterapp/gymtrainerappapp/generatedweightwidget/generated/GeneratedSpinnerWidget3.dart';
import 'package:flutterapp/gymtrainerappapp/generatedweightwidget/generated/GeneratedTextWidget18.dart';

/* Frame Weight
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWeightWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 714.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 54.0,
                child: GeneratedButtonsWidget7(),
              ),
              Positioned(
                left: 4.999999046325684,
                top: 319.0,
                right: null,
                bottom: null,
                width: 365.0,
                height: 166.0,
                child: GeneratedSpinnerWidget3(),
              ),
              Positioned(
                left: 56.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 58.0,
                child: GeneratedTextWidget18(),
              )
            ]),
      ),
    ));
  }
}
