import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedvideowidget/generated/GeneratedPlayerWidget1.dart';
import 'package:flutterapp/gymtrainerappapp/generatedvideowidget/generated/GeneratedVideoWidget1.dart';
import 'package:flutterapp/gymtrainerappapp/generatedvideowidget/generated/GeneratedCircleLeftWidget11.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/gymtrainerappapp/generatedvideowidget/generated/GeneratedImageWidget2.dart';

/* Frame Video
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVideoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height = constraints.maxHeight;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedImageWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.29802955665024633;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.7019704433497537,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedVideoWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 32.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedCircleLeftWidget11(),
              ),
              Positioned(
                left: 24.0,
                top: 655.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 125.0,
                child: GeneratedPlayerWidget1(),
              )
            ]),
      ),
    ));
  }
}
