import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedreviewswidget/generated/GeneratedHeaderWidget13.dart';
import 'package:flutterapp/gymtrainerappapp/generatedreviewswidget/generated/GeneratedReviewsWidget1.dart';
import 'package:flutterapp/gymtrainerappapp/generatedreviewswidget/generated/GeneratedRectangleWidget127.dart';
import 'package:flutterapp/gymtrainerappapp/generatedreviewswidget/generated/GeneratedButtonWidget7.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/gymtrainerappapp/generatedreviewswidget/generated/GeneratedTabsWidget1.dart';
import 'package:flutterapp/gymtrainerappapp/generatedreviewswidget/generated/GeneratedRatingGraphicWidget.dart';

/* Frame Reviews
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedReviewsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 672.0,
                child: GeneratedReviewsWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.872;

                  final double height =
                      constraints.maxHeight * 0.034482758620689655;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.13793103448275862,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTabsWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 32.0,
                top: 171.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 75.0,
                child: GeneratedRatingGraphicWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 1.0;
                  double scaleX = (constraints.maxWidth * percentWidth) / 375.0;

                  double percentHeight = 0.23275862068965517;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 189.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX:
                            constraints.maxWidth * 0.0013333333333333333,
                        translateY: constraints.maxHeight * 0.7672413793103449,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedRectangleWidget127())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7013333333333334;

                  final double height =
                      constraints.maxHeight * 0.06157635467980296;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14933333333333335,
                        y: constraints.maxHeight * 0.8990147783251231,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedButtonWidget7(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 214.0,
                height: 32.0,
                child: GeneratedHeaderWidget13(),
              )
            ]),
      ),
    ));
  }
}
