import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedinsightwidget1/generated/GeneratedNavigationBarWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/gymtrainerappapp/generatedinsightwidget1/generated/Generated59Widget4.dart';
import 'package:flutterapp/gymtrainerappapp/generatedinsightwidget1/generated/GeneratedDatePickerWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatedinsightwidget1/generated/GeneratedFinishedWorkoutWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatedinsightwidget1/generated/GeneratedGraphicsWidget.dart';

/* Frame Insight
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInsightWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.872;

                  final double height =
                      constraints.maxHeight * 0.24507389162561577;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.6834975369458128,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFinishedWorkoutWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 233.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 291.0,
                child: GeneratedGraphicsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 203.0,
                child: GeneratedDatePickerWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.11330049261083744;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.8866995073891626,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedNavigationBarWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 291.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: Generated59Widget4(),
              )
            ]),
      ),
    ));
  }
}
