import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedgender2widget/generated/GeneratedGenderWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatedgender2widget/generated/GeneratedButtonsWidget9.dart';
import 'package:flutterapp/gymtrainerappapp/generatedgender2widget/generated/GeneratedTextWidget20.dart';

/* Frame Gender 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGender2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 34.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 74.0,
                child: GeneratedTextWidget20(),
              ),
              Positioned(
                left: 117.0,
                top: 262.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 324.0,
                child: GeneratedGenderWidget(),
              ),
              Positioned(
                left: 224.0,
                top: 718.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 50.0,
                child: GeneratedButtonsWidget9(),
              )
            ]),
      ),
    ));
  }
}
