import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedfitnessinstructorswidget/generated/GeneratedTrainersWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatedfitnessinstructorswidget/generated/GeneratedHeaderWidget14.dart';

/* Frame Fitness Instructors
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFitnessInstructorsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 768.0,
                child: GeneratedTrainersWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 269.0,
                height: 32.0,
                child: GeneratedHeaderWidget14(),
              )
            ]),
      ),
    ));
  }
}
