import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedhomewidget9/generated/GeneratedCardsWidget1.dart';
import 'package:flutterapp/gymtrainerappapp/generatedhomewidget9/generated/GeneratedTextWidget13.dart';
import 'package:flutterapp/gymtrainerappapp/generatedhomewidget9/generated/Generated59Widget7.dart';
import 'package:flutterapp/gymtrainerappapp/generatedhomewidget9/generated/GeneratedNavigationBarWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/gymtrainerappapp/generatedhomewidget9/generated/GeneratedCardwithTitleWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatedhomewidget9/generated/GeneratedTabsWidget3.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.744;

                  final double height =
                      constraints.maxHeight * 0.5344827586206896;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.5763546798029556,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCardsWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.872;

                  final double height =
                      constraints.maxHeight * 0.034482758620689655;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.5221674876847291,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTabsWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 197.0,
                child: GeneratedCardwithTitleWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.872;

                  final double height =
                      constraints.maxHeight * 0.7672413793103449;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.07389162561576355,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTextWidget13(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.11330049261083744;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.8866995073891626,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedNavigationBarWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 291.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: Generated59Widget7(),
              )
            ]),
      ),
    ));
  }
}
