import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedonboarding1widget/generated/GeneratedBackgroundWidget18.dart';
import 'package:flutterapp/gymtrainerappapp/generatedonboarding1widget/generated/GeneratedIndicatorWidget2.dart';

/* Frame Onboarding 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnboarding1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 586.0,
                child: GeneratedBackgroundWidget18(),
              ),
              Positioned(
                left: 143.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 4.0,
                child: GeneratedIndicatorWidget2(),
              )
            ]),
      ),
    ));
  }
}
