import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedverificationwidget/generated/GeneratedDarkKeyboardWidget1.dart';
import 'package:flutterapp/gymtrainerappapp/generatedverificationwidget/generated/GeneratedCheckyouremailWevesentyouthePINatyouremailWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatedverificationwidget/generated/GeneratedDidyoureceiveanycodeWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatedverificationwidget/generated/GeneratedDefaultButtonWidget11.dart';
import 'package:flutterapp/gymtrainerappapp/generatedverificationwidget/generated/GeneratedInputWidget10.dart';
import 'package:flutterapp/gymtrainerappapp/generatedverificationwidget/generated/GeneratedCircleLeftWidget22.dart';
import 'package:flutterapp/gymtrainerappapp/generatedverificationwidget/generated/GeneratedVerificationWidget1.dart';

/* Frame Verification
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVerificationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 291.0,
                child: GeneratedDarkKeyboardWidget1(),
              ),
              Positioned(
                left: 56.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 50.0,
                child: GeneratedDefaultButtonWidget11(),
              ),
              Positioned(
                left: 32.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 191.0,
                height: 35.0,
                child: GeneratedVerificationWidget1(),
              ),
              Positioned(
                left: 34.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 34.0,
                child:
                    GeneratedCheckyouremailWevesentyouthePINatyouremailWidget(),
              ),
              Positioned(
                left: 106.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 18.0,
                child: GeneratedDidyoureceiveanycodeWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 311.0001525878906,
                height: 60.0,
                child: GeneratedInputWidget10(),
              ),
              Positioned(
                left: 24.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedCircleLeftWidget22(),
              )
            ]),
      ),
    ));
  }
}
