import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedlogin2widget/generated/Generated59Widget8.dart';
import 'package:flutterapp/gymtrainerappapp/generatedlogin2widget/generated/GeneratedButtonsWidget2.dart';
import 'package:flutterapp/gymtrainerappapp/generatedlogin2widget/generated/GeneratedInputsWidget5.dart';
import 'package:flutterapp/gymtrainerappapp/generatedlogin2widget/generated/GeneratedTabsWidget6.dart';
import 'package:flutterapp/gymtrainerappapp/generatedlogin2widget/generated/GeneratedProfilePictureWidget20.dart';
import 'package:flutterapp/gymtrainerappapp/generatedlogin2widget/generated/GeneratedBackgroundWidget10.dart';

/* Frame Login 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogin2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 460.0,
                child: GeneratedBackgroundWidget10(),
              ),
              Positioned(
                left: 32.0,
                top: 714.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 54.0,
                child: GeneratedButtonsWidget2(),
              ),
              Positioned(
                left: 32.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 176.0,
                child: GeneratedInputsWidget5(),
              ),
              Positioned(
                left: 32.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 26.0,
                child: GeneratedTabsWidget6(),
              ),
              Positioned(
                left: 287.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 56.0,
                child: GeneratedProfilePictureWidget20(),
              ),
              Positioned(
                left: 290.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: Generated59Widget8(),
              )
            ]),
      ),
    ));
  }
}
