import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/gymtrainerappapp/generatedproprofilewidget/generated/Generated59Widget1.dart';
import 'package:flutterapp/gymtrainerappapp/generatedproprofilewidget/generated/GeneratedProfileWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatedproprofilewidget/generated/GeneratedNameWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatedproprofilewidget/generated/GeneratedCircleLeftWidget7.dart';
import 'package:flutterapp/gymtrainerappapp/generatedproprofilewidget/generated/GeneratedInfoWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatedproprofilewidget/generated/GeneratedOptionsWidget3.dart';

/* Frame Pro Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 197.0,
                top: 122.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 104.5,
                child: GeneratedInfoWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3466666666666667;

                  final double height =
                      constraints.maxHeight * 0.10467980295566502;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.08533333333333333,
                        y: constraints.maxHeight * 0.2869458128078818,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedNameWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedCircleLeftWidget7(),
              ),
              Positioned(
                left: 32.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 104.0,
                child: GeneratedProfileWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 425.0,
                child: GeneratedOptionsWidget3(),
              ),
              Positioned(
                left: 44.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: Generated59Widget1(),
              )
            ]),
      ),
    ));
  }
}
