import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedpaymentwidget/generated/GeneratedDetailsWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatedpaymentwidget/generated/GeneratedPaymentMethodWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/gymtrainerappapp/generatedpaymentwidget/generated/GeneratedButtonWidget4.dart';
import 'package:flutterapp/gymtrainerappapp/generatedpaymentwidget/generated/GeneratedImageWidget6.dart';
import 'package:flutterapp/gymtrainerappapp/generatedpaymentwidget/generated/GeneratedHeaderWidget10.dart';

/* Frame Payment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaymentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7013333333333334;

                  final double height =
                      constraints.maxHeight * 0.06157635467980296;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14933333333333335,
                        y: constraints.maxHeight * 0.8990147783251231,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedButtonWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 207.0,
                child: GeneratedPaymentMethodWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 217.0,
                height: 32.0,
                child: GeneratedHeaderWidget10(),
              ),
              Positioned(
                left: 24.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 255.0,
                child: GeneratedDetailsWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedImageWidget6(),
              )
            ]),
      ),
    ));
  }
}
