import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedwriteareviewwidget/generated/GeneratedButtonWidget6.dart';
import 'package:flutterapp/gymtrainerappapp/generatedwriteareviewwidget/generated/GeneratedHeaderWidget12.dart';
import 'package:flutterapp/gymtrainerappapp/generatedwriteareviewwidget/generated/GeneratedRatingWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatedwriteareviewwidget/generated/GeneratedDarkKeyboardWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatedwriteareviewwidget/generated/GeneratedReviewWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Write a Review
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWriteaReviewWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 291.0,
                child: GeneratedDarkKeyboardWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7013333333333334;

                  final double height =
                      constraints.maxHeight * 0.06157635467980296;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14933333333333335,
                        y: constraints.maxHeight * 0.5406403940886699,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedButtonWidget6(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 235.0,
                child: GeneratedReviewWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 58.0,
                child: GeneratedRatingWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 256.0,
                height: 32.0,
                child: GeneratedHeaderWidget12(),
              )
            ]),
      ),
    ));
  }
}
