import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedsplashwidget/generated/GeneratedLogoWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatedsplashwidget/generated/GeneratedMaskgroupWidget.dart';

/* Frame Splash
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 41.0,
                top: 446.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 122.0,
                child: GeneratedLogoWidget(),
              ),
              Positioned(
                left: 129.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 116.0,
                child: GeneratedMaskgroupWidget(),
              )
            ]),
      ),
    ));
  }
}
