import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedsignup2widget/generated/GeneratedTabsWidget4.dart';
import 'package:flutterapp/gymtrainerappapp/generatedsignup2widget/generated/GeneratedBackgroundWidget6.dart';
import 'package:flutterapp/gymtrainerappapp/generatedsignup2widget/generated/GeneratedButtonsWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatedsignup2widget/generated/GeneratedInputsWidget3.dart';

/* Frame Sign Up 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignUp2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 384.0,
                child: GeneratedBackgroundWidget6(),
              ),
              Positioned(
                left: 32.0,
                top: 714.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 54.0,
                child: GeneratedButtonsWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 26.0,
                child: GeneratedTabsWidget4(),
              ),
              Positioned(
                left: 32.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 220.0,
                child: GeneratedInputsWidget3(),
              )
            ]),
      ),
    ));
  }
}
