import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatededitprofilewidget30/generated/GeneratedEllipse37Widget.dart';
import 'package:flutterapp/gymtrainerappapp/generatededitprofilewidget30/generated/GeneratedInputWidget1.dart';
import 'package:flutterapp/gymtrainerappapp/generatededitprofilewidget30/generated/GeneratedHeaderWidget6.dart';
import 'package:flutterapp/gymtrainerappapp/generatededitprofilewidget30/generated/GeneratedCameraWidget1.dart';
import 'package:flutterapp/gymtrainerappapp/generatededitprofilewidget30/generated/GeneratedRectangleWidget36.dart';
import 'package:flutterapp/gymtrainerappapp/generatededitprofilewidget30/generated/GeneratedButtonWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatededitprofilewidget30/generated/GeneratedInputWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatededitprofilewidget30/generated/GeneratedGroup17Widget.dart';
import 'package:flutterapp/gymtrainerappapp/generatededitprofilewidget30/generated/Generated59Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Edit Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEditProfileWidget30 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 60.0,
                child: GeneratedInputWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.8293333333333334;
                  double scaleX = (constraints.maxWidth * percentWidth) / 311.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.08533333333333333,
                        translateY: constraints.maxHeight * 0.35467980295566504,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: 1,
                        scaleZ: 1,
                        child: GeneratedRectangleWidget36())
                  ]);
                }),
              ),
              Positioned(
                left: 32.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 60.0,
                child: GeneratedInputWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7013333333333334;

                  final double height =
                      constraints.maxHeight * 0.06157635467980296;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14933333333333335,
                        y: constraints.maxHeight * 0.8990147783251231,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 32.0,
                child: GeneratedHeaderWidget6(),
              ),
              Positioned(
                left: 217.19970703125,
                top: 217.19970703125,
                right: null,
                bottom: null,
                width: 27.599998474121094,
                height: 27.599998474121094,
                child: GeneratedGroup17Widget(),
              ),
              Positioned(
                left: 127.0,
                top: 122.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 120.0,
                child: Generated59Widget(),
              ),
              Positioned(
                left: 217.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: GeneratedEllipse37Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06133333333333333;
                  double scaleX = (constraints.maxWidth * percentWidth) / 23.0;

                  double percentHeight = 0.02549260942806751;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      20.69999885559082;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.6093333333333333,
                        translateY: constraints.maxHeight * 0.2569574064809113,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedCameraWidget1())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
