import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedonboarding2widget/generated/GeneratedIndicatorWidget1.dart';
import 'package:flutterapp/gymtrainerappapp/generatedonboarding2widget/generated/GeneratedBackgroundWidget16.dart';

/* Frame Onboarding 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnboarding2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 586.0,
                child: GeneratedBackgroundWidget16(),
              ),
              Positioned(
                left: 142.99990844726562,
                top: 744.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 4.0,
                child: GeneratedIndicatorWidget1(),
              )
            ]),
      ),
    ));
  }
}
