import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedlanguagewidget/generated/GeneratedSearchWidget1.dart';
import 'package:flutterapp/gymtrainerappapp/generatedlanguagewidget/generated/GeneratedHeaderWidget1.dart';
import 'package:flutterapp/gymtrainerappapp/generatedlanguagewidget/generated/GeneratedLanguagesWidget1.dart';

/* Frame Language
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLanguageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 225.0,
                height: 32.0,
                child: GeneratedHeaderWidget1(),
              ),
              Positioned(
                left: 32.0,
                top: 192.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 680.0,
                child: GeneratedLanguagesWidget1(),
              ),
              Positioned(
                left: 32.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 40.0,
                child: GeneratedSearchWidget1(),
              )
            ]),
      ),
    ));
  }
}
