import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedtrainerdetailwidget/generated/GeneratedButtonWidget8.dart';
import 'package:flutterapp/gymtrainerappapp/generatedtrainerdetailwidget/generated/Generated59Widget5.dart';
import 'package:flutterapp/gymtrainerappapp/generatedtrainerdetailwidget/generated/Generated63Widget.dart';
import 'package:flutterapp/gymtrainerappapp/generatedtrainerdetailwidget/generated/GeneratedReviewsWidget2.dart';
import 'package:flutterapp/gymtrainerappapp/generatedtrainerdetailwidget/generated/GeneratedTextWidget7.dart';
import 'package:flutterapp/gymtrainerappapp/generatedtrainerdetailwidget/generated/GeneratedCallButtonWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatedtrainerdetailwidget/generated/GeneratedBackgroundWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/gymtrainerappapp/generatedtrainerdetailwidget/generated/Generated40Widget.dart';
import 'package:flutterapp/gymtrainerappapp/generatedtrainerdetailwidget/generated/GeneratedInfoWidget2.dart';
import 'package:flutterapp/gymtrainerappapp/generatedtrainerdetailwidget/generated/GeneratedCircleLeftWidget19.dart';
import 'package:flutterapp/gymtrainerappapp/generatedtrainerdetailwidget/generated/Generated47Widget2.dart';

/* Frame Trainer Detail
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTrainerDetailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 1.019704433497537;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedBackgroundWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.37333333333333335;

                  final double height =
                      constraints.maxHeight * 0.05788177339901478;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.3066502463054187,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTextWidget7(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 86.0,
                child: GeneratedInfoWidget2(),
              ),
              Positioned(
                left: 297.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 54.0,
                child: GeneratedCallButtonWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7013333333333334;

                  final double height =
                      constraints.maxHeight * 0.06157635467980296;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14933333333333335,
                        y: constraints.maxHeight * 0.8990147783251231,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedButtonWidget8(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 453.0,
                right: null,
                bottom: null,
                width: 646.0,
                height: 245.0,
                child: GeneratedReviewsWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedCircleLeftWidget19(),
              ),
              Positioned(
                left: 100.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: Generated59Widget5(),
              ),
              Positioned(
                left: 76.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: Generated40Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: Generated63Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: Generated47Widget2(),
              )
            ]),
      ),
    ));
  }
}
