import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedappointmentwidget1/generated/GeneratedImageWidget8.dart';
import 'package:flutterapp/gymtrainerappapp/generatedappointmentwidget1/generated/GeneratedButtonWidget5.dart';
import 'package:flutterapp/gymtrainerappapp/generatedappointmentwidget1/generated/GeneratedDatePickerWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/gymtrainerappapp/generatedappointmentwidget1/generated/GeneratedTrainerCardWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatedappointmentwidget1/generated/GeneratedHeaderWidget11.dart';

/* Frame Appointment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAppointmentWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 96.0,
                child: GeneratedTrainerCardWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7013333333333334;

                  final double height =
                      constraints.maxHeight * 0.06157635467980296;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14933333333333335,
                        y: constraints.maxHeight * 0.8990147783251231,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedButtonWidget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 410.0,
                child: GeneratedDatePickerWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 32.0,
                child: GeneratedHeaderWidget11(),
              ),
              Positioned(
                left: 42.0,
                top: 129.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 64.0,
                child: GeneratedImageWidget8(),
              )
            ]),
      ),
    ));
  }
}
