import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedprofilewidget1/generated/GeneratedNameWidget1.dart';
import 'package:flutterapp/gymtrainerappapp/generatedprofilewidget1/generated/GeneratedInfoWidget1.dart';
import 'package:flutterapp/gymtrainerappapp/generatedprofilewidget1/generated/GeneratedPremiumLinkWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/gymtrainerappapp/generatedprofilewidget1/generated/GeneratedOptionsWidget4.dart';
import 'package:flutterapp/gymtrainerappapp/generatedprofilewidget1/generated/GeneratedProfileWidget2.dart';
import 'package:flutterapp/gymtrainerappapp/generatedprofilewidget1/generated/GeneratedCircleLeftWidget8.dart';
import 'package:flutterapp/gymtrainerappapp/generatedprofilewidget1/generated/Generated59Widget2.dart';

/* Frame Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.872;

                  final double height =
                      constraints.maxHeight * 0.1022167487684729;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.7093596059113301,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPremiumLinkWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3466666666666667;

                  final double height =
                      constraints.maxHeight * 0.10591133004926108;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.07466666666666667,
                        y: constraints.maxHeight * 0.2869458128078818,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedNameWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 28.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 104.0,
                child: GeneratedProfileWidget2(),
              ),
              Positioned(
                left: 197.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 103.5,
                child: GeneratedInfoWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedCircleLeftWidget8(),
              ),
              Positioned(
                left: 32.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 425.0,
                child: GeneratedOptionsWidget4(),
              ),
              Positioned(
                left: 40.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: Generated59Widget2(),
              )
            ]),
      ),
    ));
  }
}
