import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatednotificationswidget1/generated/GeneratedNotificationsWidget2.dart';
import 'package:flutterapp/gymtrainerappapp/generatednotificationswidget1/generated/GeneratedDeleteWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatednotificationswidget1/generated/GeneratedVector1Widget1.dart';
import 'package:flutterapp/gymtrainerappapp/generatednotificationswidget1/generated/GeneratedTabsWidget.dart';
import 'package:flutterapp/gymtrainerappapp/generatednotificationswidget1/generated/Generated59Widget3.dart';
import 'package:flutterapp/gymtrainerappapp/generatednotificationswidget1/generated/GeneratedVector2Widget.dart';
import 'package:flutterapp/gymtrainerappapp/generatednotificationswidget1/generated/GeneratedNotifications2Widget.dart';
import 'package:flutterapp/gymtrainerappapp/generatednotificationswidget1/generated/GeneratedNavigationBarWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/gymtrainerappapp/generatednotificationswidget1/generated/GeneratedNotifications3Widget.dart';
import 'package:flutterapp/gymtrainerappapp/generatednotificationswidget1/generated/GeneratedHeaderWidget7.dart';

/* Frame Notifications
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNotificationsWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.11330049261083744;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.8866995073891626,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedNavigationBarWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 17.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 63.0,
                child: GeneratedNotificationsWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth - 48.0;
                  final double scaleX = width <= 0 ? 0 : (width / 327.0);

                  final double height = constraints.maxHeight - 812.0;
                  final double scaleY = height <= 0 ? 0 : (height / 0.0);

                  final Widget child = GeneratedVector1Widget1();
                  return Stack(children: [
                    Transform(
                      transform: Matrix4(scaleX, 0, 0, 0, 0, scaleY, 0, 0, 0, 0,
                          1, 0, 24.0 * scaleX, 177.0 * scaleY, 0, 1),
                      alignment: Alignment.topLeft,
                      child: SizedBox.expand(child: child),
                    )
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth - 48.0;
                  final double scaleX = width <= 0 ? 0 : (width / 327.0);

                  final double height = constraints.maxHeight - 812.0;
                  final double scaleY = height <= 0 ? 0 : (height / 0.0);

                  final Widget child = GeneratedVector2Widget();
                  return Stack(children: [
                    Transform(
                      transform: Matrix4(scaleX, 0, 0, 0, 0, scaleY, 0, 0, 0, 0,
                          1, 0, -16.0 * scaleX, 435.0 * scaleY, 0, 1),
                      alignment: Alignment.topLeft,
                      child: SizedBox.expand(child: child),
                    )
                  ]);
                }),
              ),
              Positioned(
                left: 17.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 84.0,
                child: GeneratedNotifications2Widget(),
              ),
              Positioned(
                left: -32.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 47.0,
                child: GeneratedNotifications3Widget(),
              ),
              Positioned(
                left: 311.0,
                top: 356.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 79.0,
                child: GeneratedDeleteWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.872;

                  final double height =
                      constraints.maxHeight * 0.034482758620689655;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.1440886699507389,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTabsWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.456;

                  final double height =
                      constraints.maxHeight * 0.03078817733990148;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.272,
                        y: constraints.maxHeight * 0.06896551724137931,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedHeaderWidget7(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 291.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: Generated59Widget3(),
              )
            ]),
      ),
    ));
  }
}
