import 'package:flutter/material.dart';
import 'package:flutterapp/gymtrainerappapp/generatedheightwidget/generated/GeneratedSpinnerWidget2.dart';
import 'package:flutterapp/gymtrainerappapp/generatedheightwidget/generated/GeneratedTextWidget17.dart';
import 'package:flutterapp/gymtrainerappapp/generatedheightwidget/generated/GeneratedButtonsWidget6.dart';

/* Frame Height
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHeightWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 28, 28, 30),
                ),
              ),
              Positioned(
                left: 53.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 269.0,
                height: 58.0,
                child: GeneratedTextWidget17(),
              ),
              Positioned(
                left: 32.0,
                top: 714.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 54.0,
                child: GeneratedButtonsWidget6(),
              ),
              Positioned(
                left: 109.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 350.0,
                child: GeneratedSpinnerWidget2(),
              )
            ]),
      ),
    ));
  }
}
